language: python
python: 3.8

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python-pip
  - pip install pytest
  - pip install selenium
  - pip install coverage
  - pip install geckodriver-autoinstaller
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  
script:
   - python3 -m pytest
   - coverage run -m pytest
   - coverage report 2>&1 

after_success:
  - pip install coveralls
  - coveralls
