language: python
python: 3.8

addons:
  firefox: "latest"
  
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python3.8.7/lib/python3.8/site-packagess
  
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python-pip
  - pip install pytest
  - pip install selenium
  - pip install coverage
  
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux32.tar.gz
  - mkdir $HOME/geckodriver 
  - tar xvf /tmp/geckodriver.tar.gz -C $HOME/geckodriver
  - export PATH=$HOME/geckodriver:$PATH


  
script:

   - python3 -m pytest
   - coverage run -m pytest
   - coverage report 2>&1 

after_success:
  - pip install coveralls
  - coveralls
